### ISSUE TITLE
Incrementing variable in custom script increments other variables not targetted

### ISSUE THREAD

**Issue by joeledge** [chrismaltby/gb-studio#1033]
**Describe the bug**
A script that increments one variable on button attachment, updates the other variables in the custom event that shouldn't be targetted, however when outside of a custom event (on init) works correctly

**To Reproduce**
1. Create a custom event attaching on press to select
2. Increment one variable on press
3. Output that variable along with other variables in a dialogue

**Expected behavior**
Just the targeted variable to be incremented by one

**Screenshots**
<img width="425" alt="Screenshot 2022-01-28 at 15 02 55" src="https://user-images.githubusercontent.com/28432913/151570493-1e3a3637-0000-49f3-9ee9-d6df12beffc0.png">

**Platform (please complete the following information):**
 - OS: MacOS 11.6.2
 - App version 3.0.3

**Comment by um3k** [comment]
I did a bit of testing, I found that if you move the Attach Script event out of the custom script, putting it into init and then putting the Call Script inside it, it works correctly. I then edited the dialogue GBVM code to output the variable indexes instead of their values, and found that they were all 0. I do not understand the nuts and bolts of how it all works, but it's clear that the custom script is not correctly passing its VM context on to the input script.
