### ISSUE TITLE
"set player spritesheet" bug

### ISSUE THREAD

**Issue by Zanilo** [chrismaltby/gb-studio#1139]
**Describe the bug**
The function "set player spritesheet" to change the sprite of the player when he press a button bugs. When the spritesheet changes, the sprite appears with a lot of square images. Its possible to use "set animation state" to substitute that, but it will eventually surpass the frame limit of the scene.

**To Reproduce**
1. Attach script to "x" button
2. Set player spirtesheet.
3. Attach script to "left/right" button override default button action
4. Launch projectile
5. wait for 0.2 sec
6. remove left/right button script
7. Set player spritesheet to default
8. wait 0.3 sec
9. See error

**Expected behavior**
The sprite of the player will change when you press "x" button, but it will bug, and later return to normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/78191734/177110199-29d221cb-ec46-41a3-8083-3b413c55e41e.png)
![image](https://user-images.githubusercontent.com/78191734/177109944-32a57548-ea79-4ddb-8647-afef6e42520d.png)
![image](https://user-images.githubusercontent.com/78191734/177110127-c95942ae-6554-4336-ac53-0cd6f9f3041b.png)

**Platform (please complete the following information):**
 - Windows
 - App version GBSTUDIO 3.0.3 Lateste version so far

**Comment by RichardULZ** [comment]
This is a side effect of modifying already in use vram with set sprite sheet, you already have the work around which is using animation states, pre allocated vram similar to 2.0 and prior, but yes, you'll run out of vram. 

You can switch to a hidden state and gbvm VM_IDLE before the switch so you see nothing instead of inbetween vram data. Smaller sheets will load faster, but still not fast enough.

Keeping sprites set up in a similar order, or having an idle fall back state as the first thing in every sheet, that you can switch to in hopes the layout stays identical between sprites, may be another work around.

We could add some kind of algorithm that compares all sprites for reused tiles, and tries to keep those repeated tiles in the same order between other sprites, so it's more likely to not have visible garbage, but it will not cover all cases and is mostly unfixable, apart from hiding the actor, or using more vram.

**Comment by Zanilo** [comment]
I tried most of that, unfortunally only the animation state works well. I guess its impossible of now to make a fighting game for game boy in gbstudio so I will try to reuse the sprites for a platform that have less moves. Thanks for the help!
