### ISSUE TITLE
[Bug] Window frame of Display text is unexpected display.

### ISSUE THREAD

**Issue by kurosukee** [chrismaltby/gb-studio#126]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
report a bug.

* **What is the current behavior?**
Window frame of Display text is unexpected display if add a scene by any images.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Add backgrounds image by Explorer or Finder etc. *FYI: outside_03.png
2. Add a scene that image as added by step 1.
3. Add any actor and add display text of actor script.
4. Game run.
5. Press the actor added by step 3.
6. Window frame of display text is unexpected display. (←bug) *FYI: issue_02_bug.png

* **What is the expected behavior?**

Display with correct frame window in step 6.
FYI: issue_03_expect.png

* **What is the motivation / use case for changing the behavior?**
FYI. steps

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: [macOS]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

FYI images.
issue_01.png
![issue_01](https://user-images.githubusercontent.com/44237557/57226633-6a9bd880-704a-11e9-9dfb-5f00424a08ff.png)

issue_02_bug.png
![issue_02_bug](https://user-images.githubusercontent.com/44237557/57226634-6a9bd880-704a-11e9-95b4-cff49c67d523.png)

issue_03_expect.png
![issue_03_expect](https://user-images.githubusercontent.com/44237557/57226635-6a9bd880-704a-11e9-8dac-c77f8cf38e88.png)

outside_03.png
![outside_03](https://user-images.githubusercontent.com/44237557/57226636-6b346f00-704a-11e9-9150-d118542c9a35.png)

Finally, I'm sorry that my English isn't very good

**Comment by RichardULZ** [comment]
Thank you for providing the images!
The problem is your **Background** image is **too detailed**!
The screen is made of **8x8** pixel squares, you must repeat many squares on the grid, so that the Gameboy can re-use the same **8x8** square everywhere, and leave room for the text box graphics.

Double click the Run button, you will see a lot of technical words, but the orange ones are important,
![image](https://user-images.githubusercontent.com/34431457/57228589-3df6b980-7068-11e9-9c77-e93d3d2d085e.png)
`- Background 'outside_03.png.png' contains too many unique 8x8px tiles (217 where limit is 192).`

To fix this, I recommend the program **Tiled**, https://www.mapeditor.org/

+ Create a new file, 32x32 map, 8x8 tile size. 
![image](https://user-images.githubusercontent.com/34431457/57228809-c9704a80-7068-11e9-94cc-8540634260d7.png)
+ Press, New Tileset...  Find your background, make sure it is 8px by 8px
![image](https://user-images.githubusercontent.com/34431457/57229031-47345600-7069-11e9-9544-18f530774f1f.png)
+ Select everything in the tileset, then click in the map window.
![image](https://user-images.githubusercontent.com/34431457/57229107-721eaa00-7069-11e9-9990-447ae8ee70b6.png)
+ Then pick one square on the tile set, and place it on the map in many places you can repeat.
+ "Save", and "Export as Image" to make your repeated background.

Hope you can follow that tutorial, good luck!

**Comment by Zzausch** [comment]
You can also use this tool "Gameboy Tile Data Generator" which automatically searches for the same tiles in your map and reduces the size if possible:
https://github.com/chrisantonellis/gbtdg

**Comment by kurosukee** [comment]
I have solved! thanks to your support.
