### ISSUE TITLE
Can you make a GBA studio?

### ISSUE THREAD

**Issue by hurry1102** [chrismaltby/gb-studio#1268]
I personally think that a gba studio should be made because of higher graphics capabilities and more room to work in.

**Comment by maxoakland** [comment]
GBA studio would be great but it’s not really related to GB Studio because the GBA is so different, it will be a completely different application. Maybe someone will make it but I think the GBStudio team has their hands full on GBS

**Comment by sabra55** [comment]
GBA studio would be a much, much more complex application to develop. you *could **maybe*** take the existing codebase of GB studio, but it'd take much of refactoring the engine (alongside other things) to work with the new GBA toolchain instead of GB. it'd just be a hassle, the GBA is lots more complex than the GB.

**Comment by maxoakland** [comment]
> GBA studio would be a much, much more complex application to develop. you _could **maybe**_ take the existing codebase of GB studio, but it'd take much of refactoring the engine (alongside other things) to work with the new GBA toolchain instead of GB. it'd just be a hassle, the GBA is lots more complex than the GB.

I think that would be a cool idea since GBStudio has a very good interface for Game Dev

I remember a few years ago, someone posted a very rough example of GBStudio being modified to compile for Gamegear, since the hardware is very similar. That would probably be easier than doing GBA and it would enable more colors

**Comment by win-ini** [comment]
> > GBA studio would be a much, much more complex application to develop. you _could **maybe**_ take the existing codebase of GB studio, but it'd take much of refactoring the engine (alongside other things) to work with the new GBA toolchain instead of GB. it'd just be a hassle, the GBA is lots more complex than the GB.
> 
> I think that would be a cool idea since GBStudio has a very good interface for Game Dev
> 
> I remember a few years ago, someone posted a very rough example of GBStudio being modified to compile for Gamegear, since the hardware is very similar. That would probably be easier than doing GBA and it would enable more colors

yep, the GG seems like a more feasible target.

**Comment by maxoakland** [comment]
> > > GBA studio would be a much, much more complex application to develop. you _could **maybe**_ take the existing codebase of GB studio, but it'd take much of refactoring the engine (alongside other things) to work with the new GBA toolchain instead of GB. it'd just be a hassle, the GBA is lots more complex than the GB.
> > 
> > 
> > I think that would be a cool idea since GBStudio has a very good interface for Game Dev
> > I remember a few years ago, someone posted a very rough example of GBStudio being modified to compile for Gamegear, since the hardware is very similar. That would probably be easier than doing GBA and it would enable more colors
> 
> yep, the GG seems like a more feasible target.

I'd love to see it. Anyone know what needs to happen to make this work? Is there something like GBDK for Gamegear that could be put in to compile for Gamegear?
