### ISSUE TITLE
Share tiles between maps

### ISSUE THREAD

**Issue by mills32** [chrismaltby/gb-studio#1287]
Hi, I programmed several tests and demos in GBDK, and this is great!. 

But I wonder if it is possible to share tiles for use in several maps, so that less space is used .

I can create a huge map and split it at certain points, to crate several levels, but I wanted to use smaller maps.

Thanks!.

**Comment by RichardULZ** [comment]
This has been a built in feature of gb studio since 1.0, it will attempt to merge tilesets if the total is between 128-192, to save on rom space,

You may notice in a vram debugger tiles never used on a certain screen may be loaded in vram, this is it in action. 
If that's what you were inquiring about, please close this issue :)

**Comment by mills32** [comment]
That's exactly wat I wanted to ask. Thanks a lot.
