### ISSUE TITLE
Text Box Error

### ISSUE THREAD

**Issue by grandell1234** [chrismaltby/gb-studio#1289]
Text randomly changes to something else less then a second after a text box opening. *See Screenshots*
**Screenshots**

**Platform (please com
![Screen Shot 2023-07-19 at 4 55 36 PM](https://github.com/chrismaltby/gb-studio/assets/78573365/72b11d85-26a8-4fac-ba13-87d8e7e8d0b1)
![Screen Shot 2023-07-19 at 4 56 39 PM](https://github.com/chrismaltby/gb-studio/assets/78573365/f6ddead4-414d-443b-8848-8cad774a82e8)
plete the following information):**
 - OS: macOS 11.6.1 (Same error on other devices)
 - App version latest

**Comment by RichardULZ** [comment]
This is expected behavior with too much text, but warnings in the editor would be nice.
On DMG, you have 52 tiles of ui reserved text vram, which are in a rolling buffer, this allows about 3 lines of full text. 
On GBC, there are an extra 64 tiles of vram allocated. 

I had at one point tested making the text preview turn yellow, and then red, when reaching each console's vram tile limit, but was concerned with possible lag while typing, and never pushed the feature.

I would recommend a Variable Width Font like the one included with the sample project, or this condensed font pack https://edo999.itch.io/condensed-fonts
This will improve spacing between letters, so you can fit more characters in the same amount of vram tiles.
