### ISSUE TITLE
Actor Set Direction broken

### ISSUE THREAD

**Issue by thomas-alrek** [chrismaltby/gb-studio#134]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
In the latest develop build, the Actor Set Direction event seems to be broken.
It seems to do nothing at all.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Add **Actor Set Direction** event.

* **What is the expected behavior?**
That the Actor faces the direction specified by the event.

* **Please tell us about your environment:**

  - Version: 4bc40aa2800db835cfe07c7465b77a214cd7cd81
  - Platform: macOS

**Comment by chrismaltby** [comment]
Ahh, yeah, when I switched how rendering worked I made it so you need to call the function `void SceneRenderActor_b(UBYTE i)` any time an actor should change direction but forgot to hook this up to the change direction event. I think this also would have affected changing the player sprite sheet from an event. Should now be fixed in 9343f74b27355abd625d6a43f439442a684deef5.
