### ISSUE TITLE
Actor Prefabs

### ISSUE THREAD

**Issue by marco-afonso** [chrismaltby/gb-studio#1401]
**Is your feature request related to a problem? Please describe.**
I'm frustrated with not being able to create more reusable assets like unity prefabs. I'm having to create scripts for all events, placing them manually and having to assign parameters to access local vars. It is very time consuming and if I create a new local var it wont be magically assign to all custom scripts inside all my objects. I've noticed there was a branch for this too! https://github.com/chrismaltby/gb-studio/compare/develop...feat/prefab 

**Describe the solution you'd like**
Would like to have a new panel where I can drag actors to create prefabs. Then, I would like to drag and drop them in any scene I'd like. I understand that in these prefabs, I would not have access to actor references since they could be placed in any scene. However, I would like them to have their own instances of local vars at runtime so that, for instance, when the player picks a flower in one place, it doesn't get removed from anywhere else.

**Describe alternatives you've considered**
Creating custom scripts for all actor events and passing local vars as parameters and assign everything manually

**Additional context**

**Comment by HeyItsLollie** [comment]
There was some discussion between gamedev (that is, not the GBS devs) in the GB Studio Discord server's "feature-ideas" channel last week (May 24) about the potential of splitting up the project .json into smaller separate .json files, which also grew into a discussion about actor prefabs.

Discord: GB Studio > #feature-ideas
https://discord.com/channels/554713715442712616/570925583421276160/1243612006024609803

This is a hugely-truncated snip of the discussion, just to share the core ideas (without having to join a server to read them, lol).
I'll denote truncated sections with `[...]`.
```
SōdoDev:
  this is more of a long term feature but

  a revamp of how gbs handles project files

  right now it's not very git friendly and having everything be
  inside a single json that can get really big worked in the first
  few versions, for smaller games

  but right now, with games getting bigger and teams of more than
  one or two people working on them, it's not ideal

  perhaps some stuff like palette data or collisions and stuff like
  that could be moved to different project files

ZoneBooth:
  I would want something like each scene script and actor to have
  it's own json file, and similar compartmentalizing all over

[...]

Lollie:
  Decoupling actors from scenes would be a really good thing in the
  long run. Treating actors like assets that can be referenced in
  any scene, effectively prefabs.

  If an actor could be stored as one json asset, a scene could
  contain multiple references to that one json, along with any
  event/variable overrides for each reference.

[...]

gud_graphics:
  In this paradigm you would create an NPC actor, it is listed in
  an Actors menu alongside scenes, variables, scripts. You can
  define a set of base behaviors. And then when you add it to a
  scene, you can override the art, dialog, etc.

  The dream would be you could select any event block and select
  like "override" to replace it with another event block or
  "ignore". By using event groups, users could have a lot of
  control over the modularity of this.

  And anything you add or change is marked as dirty by some little
  icon to let you know you have deviated from the base actor

[...]

ZoneBooth:
  .project/
  ├── about.json
  ├── actors
  │   └── actor_1
  │       ├── script.json
  │       └── settings.json
  ├── scene_1
  │   ├── actors
  │   │   └── actor_1
  │   │       ├── script.json
  │   │       └── settings.json
  │   ├── script.json
  │   └── settings.json
  └── settings.json

  with `scene_1/actors_actor_1` being an actor local to `scene_1`
```

**Comment by chrismaltby** [comment]
Both prefabs @marco-afonso and project splitting like you're suggesting here @HeyItsLollie have been on my backlog for some time and absolutely things that I'll be working on. Both features were mostly held back as I needed to do large refactor of the codebase recently, converting most of the application to Typescript in the process but I'm at the point where I could start looking at both of these again now.

I believe where I got to previously with prefabs, was getting stuck on how best to handle overrides, so if you had a prefab actor that was instanced multiple times but you each one had small changes (or extra events) in the script for example. I think the move to Typescript will make it much easier to handle all the different edge cases that this modification would introduce though.

 And as for splitting the project file, what's suggested above was close to what I was thinking. The things I was trying to work out were things like:
- When you rename a scene in app should the files also get renamed (scene_1 in your example)? If so when does the rename happen? In researching how [Godot](https://godotengine.org) does it, they rename the corresponding files as soon as you rename in the app and then save any files that reference them instantly. Could do this but it's a change to how saving normally works (only when you explicitly decide to). I'm leaning towards only modifying files on disk when choosing to save.
- Should editing the json files outside of GB Studio live update the application? If so how to handle things like conflicts where you have unsaved changes in app
- What folder should these files be in? I like that idea of having `.project` though being a dotfile I could see if being easy to not realise it's there on systems that hide it by default and trying to zip up the project + assets and not understand why it's broken. Maybe just `project` is fine though

These are just a few things of the top of my head, there's definitely a lot to consider and it can introduce a few more ways for people to accidentally break their project if not careful. I'll work through them though as it's the right way to go longer term.

Either way both of these features will be after the 4.0 release. I'm starting to wrap up on what will make it in now and these would both require significant dev work.

Happy to continue to discuss both features here though as I continue to work out how best to approach the implementation.

**Comment by HeyItsLollie** [comment]
That's great to hear! Completely understand them being post-4.0 — even without the refactors, they're a big overhaul of how assets and projects are currently structured. 

> * When you rename a scene in app should the files also get renamed (scene_1 in your example)? If so when does the rename happen?

I would lean towards allowing GB Studio to rename files immediately, as this would be an edit made directly via the project. Just like Godot, Unity also behaves this way; in Unity's case if I recall correctly, every asset in a project is given an ID/hash on import, and so in the back-end, scenes and objects reference the ID instead of the file directly (something that GB Studio already seems to do as well). I believe this approach makes it easier to keep references to renamed files up to date, as you wouldn't actually have to touch and resave any other scenes/assets that reference them — you instead update the metadata with the filename that is associated with its ID. That said, Unity's approach to metadata produces a lot of .meta files in the process. (one .meta per asset, which all have to be ignored in Git/SVN repositories.)

> * Should editing the json files outside of GB Studio live update the application? If so how to handle things like conflicts where you have unsaved changes in app

I really like Notepad++'s approach, just to give an example for how to handle external edits. When N++ regains focus, it checks the on-disk data of currently-open files against their last known state in-memory. Depending on whether a file has been changed or deleted, one of two prompts occur:
1. If the file has been updated externally, N++ asks if the user wants to reload the file.
2. If the file has been deleted (or renamed), N++ asks if the user wants to keep the file in editor.

These both serve as safeguards in the event of irreparable external changes. GB Studio probably wouldn't need to worry about 2) in the event of a renamed scene file, as long as it can check against IDs and update the project accordingly.

In this same vein, what should happen if a user decides (for whatever reason) to create a new .json externally, or duplicate an existing .json? eg: If it's a scene .json, prompt the user that a new scene has been detected, and then ask them to place it in the scene canvas?

> What folder should these files be in?

I think an openly visible `project` folder would be fine for project settings or relevant metadata, in the same way that the `assets` folder is plainly visible. But, would scene files and actors belong in `project` or `assets`? What separates project data from asset data?

What I like most about the example folder structure that ZoneBooth provided, is how it implies a clear separation between "actors" as a reusable prefab / global asset (much like sprites and palettes), VS "actors" stored inside scenes, where every scene is a folder that can contain bespoke / local assets.

**Comment by Steinbeuge** [comment]
I feel like for simplicity the designer should be setting their actor prefab up to handle different cases themselves, rather than Chris having to write a complex system that handles many cases.
For now GB Studio could simply have an actor prefab with user defined inputs (pallet, hp, speed, loot id, behaviour flag etc), that gets combined with a matching resource ref at run time. This would reduce the data stored for an actor in a scene to pos.x, pos.y, actor_address, resource_address

**Comment by HeyItsLollie** [comment]
> I feel like for simplicity the designer should be setting their actor prefab up to handle different cases themselves, rather than Chris having to write a complex system that handles many cases.

Definitely. Speaking personally, my ideal is that setting up an actor prefab would be just like setting up any other actor - the big difference would be that instead of having a complete copy of an actor's data stored inside the scene file, a prefab's data would be saved externally, and the scene would only store a reference to the prefab + any altered values. (ie: you wouldn't be able to delete or reorder events in a prefab reference, you could only change a prefab's event values.)

So ideally, no need to account for a ton of "what if" scenarios. The user would create their actor prefab the same way that they can currently create them, it'd just be saved and edited outside of a scene instead.

**Comment by maxoakland** [comment]
Prefabs have been added so you could close this issue
