### ISSUE TITLE
Scrolling state inside script no longer stored

### ISSUE THREAD

**Issue by nielsderijk** [chrismaltby/gb-studio#1414]
**Describe the bug**
Since v4.0.0 beta 1, the scrolling state of scripts is no longer stored, which means I lose track of where I am all the time. I opened 3.2 just now and noticed it was working there still.

I also noticed the script jumping up and down when I paste a script inside a script, or expand a script inside a script. Both are related to scrolling states as well.

**To Reproduce**
1. Create a long script
2. Scroll down
3. Click on another script and go back

**Expected behavior**
I expect GB Studio to remember the scrolling state inside a script so I don't have to scroll down constantly to where I left.

**Screenshots**
https://github.com/chrismaltby/gb-studio/assets/20700995/8ce3a78c-6024-47d7-906a-a775ca38e557

**Platform (please complete the following information):**
 - OS: macOS Sonoma 4.4.1
 - App version: 4.0.0 beta 2

**Additional context**
GB Studio is amazing :)

**Comment by chrismaltby** [comment]
Thanks for raising this @nielsderijk, I'm actually surprised this ever worked, looks like it was only when clicking between `Scripts` and it was just using the same scroll position for both scripts so if you were flicking between multiple scripts at a few at different positions you'd need to manually scroll up and down still.

I've managed to fix this in https://github.com/chrismaltby/gb-studio/commit/c30dc2feb05ff25857a8152969ae53b4fbc06f25 which now keeps track of the sidebar scroll position when switching (for actors/scenes/triggers also) and will preserve the scroll position. It required an update to how sidebars work (scripts now always take up the full width of the sidebar rather than switching to a second column) so hopefully this doesn't prove to be controversial. I think it ends up being a better use of space though so hopefully people agree.

Before:
<img width="565" alt="Screenshot 2024-05-22 at 11 40 39" src="https://github.com/chrismaltby/gb-studio/assets/16776042/0d042289-8d6c-45f2-8c4b-57906905f8d0">

After
<img width="592" alt="Screenshot 2024-05-22 at 11 39 20" src="https://github.com/chrismaltby/gb-studio/assets/16776042/b786cf02-7fd2-4d08-844d-26c2a267443f">

**Comment by nielsderijk** [comment]
@chrismaltby I love this new view as it removes a lot of empty space. Would pick this version over the old one any day, even more so if it saves scroll states!
