### ISSUE TITLE
VM_SET_FONT Doesn't Work Anymore [v4.0.0 beta1 - present (rc2)]

### ISSUE THREAD

**Issue by Brushman97** [chrismaltby/gb-studio#1451]
### The Issue
For the game I'm working on, I've used the GBVM operation, "VM_SET_FONT" to have there be different fonts outside of the one in the settings. However, since the first beta release of v4 and continuing into rc2, this operation no longer displays anything, or it displays a corrupted font. 
<img width="667" alt="Screenshot 2024-06-14 015329" src="https://github.com/chrismaltby/gb-studio/assets/172739123/da1c4075-1e54-4701-87bb-11c7d8ba2dc8">

(This first screenshot shows what happens when the number in VM_SET_FONT is set to 1)

<img width="679" alt="Screenshot 2024-06-14 015728" src="https://github.com/chrismaltby/gb-studio/assets/172739123/0d387a8a-e735-4cb2-aaf2-e433f541eca8">

(And this second screenshot shows what happens when it's set to 2 (or, not pictured, higher))

What I've done temporarily is set the default font to the one I've been using for my game's HUD.

<img width="381" alt="Screenshot 2024-06-14 020422" src="https://github.com/chrismaltby/gb-studio/assets/172739123/326f416a-952f-4b02-a194-50d248693aa1">

(How the HUD's meant to look)

### How To Reproduce This Issue
1. Add a new font into the project.
2. Create a blank scene.
3. Follow [this tutorial](https://gbstudiolab.neocities.org/guides/gbvm-overlay-hud) up until you get to this part:
![image](https://github.com/chrismaltby/gb-studio/assets/172739123/f17aea60-ccdc-4ff3-953d-8c5468a53c9a)
4. Place this line of code above the "VM_LOAD_TEXT 0":
"VM_SET_FONT 1" (You can mess around and see what other numbers will do, but 1 was the one that worked for me in v3.2.1)
5. Run the project and see the results. Depending on the number, you should get either a single glitchy tile, or a row of glitchy tiles.

![image](https://github.com/chrismaltby/gb-studio/assets/172739123/0ecff1ac-6b43-446b-8777-8f3f10a74959)

![image](https://github.com/chrismaltby/gb-studio/assets/172739123/bd575bbf-c705-44ea-8cc8-bc6f4a7a5b69)

**Comment by Brushman97** [comment]
Also, my apologies for all the edits I've made to this post.

**Comment by chrismaltby** [comment]
Hi @Brushman97 thanks for raising this issue. I've followed the step and am seeing the same thing. It seems the issue is that adding the font using "References" in a GBVM script block isn't causing the font to be added to the project anymore. I've spotted why this is and have a fix, I'm just confirming that other uses of "References" aren't currently broken in the same way.

Just so you know the bug seems to have been introduced here in a change that was supposed to improve fonts being imported correctly! Oops https://github.com/chrismaltby/gb-studio/commit/699ea5ea1619274c5a3491d7084950db768db763

For now while you wait for a fix, it's not great but you could:
1. make an empty scene
2. add a script to the scene init "Display Dialogue"
3. in the dialogue text type "!font" and choose your HUD font from the menu that opens
This will cause that font to be included in the project and your VM_SET_FONT calls should work as expected

**Comment by Brushman97** [comment]
> Hi @Brushman97 thanks for raising this issue. I've followed the step and am seeing the same thing. It seems the issue is that adding the font using "References" in a GBVM script block isn't causing the font to be added to the project anymore. I've spotted why this is and have a fix, I'm just confirming that other uses of "References" aren't currently broken in the same way.
> 
> Just so you know the bug seems to have been introduced here in a change that was supposed to improve fonts being imported correctly! Oops [699ea5e](https://github.com/chrismaltby/gb-studio/commit/699ea5ea1619274c5a3491d7084950db768db763)
> 
> For now while you wait for a fix, it's not great but you could:
> 
>     1. make an empty scene
> 
>     2. add a script to the scene init "Display Dialogue"
> 
>     3. in the dialogue text type "!font" and choose your HUD font from the menu that opens
>        This will cause that font to be included in the project and your VM_SET_FONT calls should work as expected

Thanks! That should do the trick for now.

**Comment by Brushman97** [comment]
The issue has now been fixed in the final version of v4.0.0.
