### ISSUE TITLE
Visual glitch with subfolders in settings

### ISSUE THREAD

**Issue by maxoakland** [chrismaltby/gb-studio#1456]
**Describe the bug**
If you have sprites in subfolders, the subfolders have a different font from sprites on the Settings page

**Expected behavior**
They should have the same font

**Screenshots**
![image](https://github.com/chrismaltby/gb-studio/assets/57502156/80bb5c51-b59a-4810-99c6-70866ac53933)

**Platform (please complete the following information):**
 - OS: Mac OS
 - App version 4 release candidate 2

**Comment by chrismaltby** [comment]
This was intentional, with the folders using a smaller font size that would wrap to a second line when the folders were very long. But in reviewing I think there's a few too many places where the alignment looks a bit weird, so I'm rolling back the change for now so folders will be the same font size and long names will not wrap. I'll have a think about better ways to layout these fields now that folders will be more common for future updates.

**Comment by maxoakland** [comment]
> This was intentional, with the folders using a smaller font size that would wrap to a second line when the folders were very long. But in reviewing I think there's a few too many places where the alignment looks a bit weird, so I'm rolling back the change for now so folders will be the same font size and long names will not wrap. I'll have a think about better ways to layout these fields now that folders will be more common for future updates.

Maybe you could make all the text use the smaller font in situations like that?
