### ISSUE TITLE
Can't Rename Variables Within Events or Statements [??? - present (v4.0.0 Final)]

### ISSUE THREAD

**Issue by Brushman97** [chrismaltby/gb-studio#1461]
### The Issue
There have been some instances where I'm unable to rename any local, temp*, or global variable without defining it. (*Are temp variables able to be renamed? I thought they were, but I don't know for sure.)

I've provided footage to demonstrate what's going on.

https://github.com/chrismaltby/gb-studio/assets/172739123/b0a208b1-66a7-4269-aeb5-332ece124d26

In this clip, I try to rename a local variable, but the pencil icon doesn't show up. However, when I add a "Variable Set To Value" event, I'm able to rename it. 

This is also the case with "If" statements:

https://github.com/chrismaltby/gb-studio/assets/172739123/d764000f-abed-4203-a87b-b979e796f345

**Comment by Brushman97** [comment]
I'm not sure if this is truly a glitch or if this behavior is intentional. If it's intentional, then I think it would be better if you could also rename your variables in these areas.

**Comment by chrismaltby** [comment]
I actually think this was originally intentional, I specifically didn't turn on the rename functionality for variables used in script values, though I forget why. It possibly was interfering with the script value UI, or maybe it didn't feel like there was enough room as the inputs get smaller, not sure.

It was a one line of code change though which I've just made and there doesn't seem to be anything broken from what I can see so I think it's safe to turn on now.

Builds with this change will shortly be available at https://github.com/chrismaltby/gb-studio/actions/runs/9698945147

**Comment by chrismaltby** [comment]
Also, to answer your other question. The two temp variables aren't able to be renamed

**Comment by Brushman97** [comment]
> I actually think this was originally intentional, I specifically didn't turn on the rename functionality for variables used in script values, though I forget why. It possibly was interfering with the script value UI, or maybe it didn't feel like there was enough room as the inputs get smaller, not sure.
> 
> It was a one line of code change though which I've just made and there doesn't seem to be anything broken from what I can see so I think it's safe to turn on now.
> 
> Builds with this change will shortly be available at https://github.com/chrismaltby/gb-studio/actions/runs/9698945147

Sorry for the late reply. Thanks for the fix!
