### ISSUE TITLE
Invert Colors Escape Sequence "\007" Combined with New Line "\n"

### ISSUE THREAD

**Issue by PaperAirship** [chrismaltby/gb-studio#1471]
**Describe the Bug**

It appears that the escape sequence modifiers for invert colors `\007` and next line `\n` were combined at some point in the documentation as `\007\n`.

![image](https://github.com/chrismaltby/gb-studio/assets/90337792/b416d324-2f78-4ee3-abce-d0aacd5ae6e9)

**To Reproduce**

Including `\007\n` as it is presented in the documentation in Display Dialogue will force a new line in the Dialogue Box preview, although during playtesting text will be inverted as expected with no new line. There is no indication to treat "n" as a value like in similarly formatted escape sequences, and replacing it with a number appears to have no effect.

![image](https://github.com/chrismaltby/gb-studio/assets/90337792/1d2aa6e8-3a1c-4505-b3d3-f9e60b25530b)

**Expected Behavior**

`\007` on it's own functions as expected and appears to be all that's required to invert text colors. 

**Additional context**

Apologies if I'm completely missing something. I was unable to find very much information about this feature beyond ones that also seem to be repeating the mistake. [This article from October 2022](https://gbstudiocentral.com/tips/understanding-fonts/) also includes `\007\n` near the end  with no further elaboration when it lists the escape sequences. It's possible that it does/did have some additional function, and the issue is just a matter of clarity, as well as a display one with the Dialogue preview still including the new line.

**App Version**

GB Studio 4.0.0

**Comment by chrismaltby** [comment]
Hi @PaperAirship I think the documentation just isn't very clear here. I'd never actually used the feature myself before so I had to look in the code to see how this was working. It looks like a value is needed after the `\007`, for example try using the text "hello\007world", you'll see in game it appears as "helloorld" because `w` was being used as the text colour value.

I think what the documentation should say is `\007\001` sets the text to use a light background, `\007\002` sets the text to use a dark background.

I'll get the documentation updated, thanks for raising this

**Comment by chrismaltby** [comment]
I've just updated the docs here to make the argument to the text inversion command clearer https://www.gbstudio.dev/docs/scripting/gbvm/gbvm-operations/#vm_load_text
