### ISSUE TITLE
GB Studio 4.0.1 serializes projects with the version string set to "4.0.0"

### ISSUE THREAD

**Issue by mxashlynn** [chrismaltby/gb-studio#1490]
**Describe the bug**
GB Studio 4.0.1 serializes projects with the version string set to "4.0.0" and reports that projects with the version string set to "4.0.1." are unsupported.

**To Reproduce**
1. Start GB Studio 4.0.1.
2. Create a new, blank project.
3. Close the project by selecting File > Switch Project.
4. Open the new .gbsproj file in a text editor.
5. Note that the 4th line reads `"_version": "4.0.0",`
6. Change this line to read `"_version": "4.0.1",`
7. Save.
8. Open the project from Recent list.

**Expected behavior**
The project opens.

**Screenshots**
![GBS 4.0.1 Not Supported on GBS Version 4.0.1](https://github.com/user-attachments/assets/88b2cfb7-ad98-4614-a6f1-292ed87ce77a)

**Platform**
 - OS: Windows 10 Pro
 - App version: 4.0.1

**Additional context**
I'm not sure if this is actually a bug or if I have misunderstood the way the version string works.

**Comment by chrismaltby** [comment]
Hi @mxashlynn thanks for raising but I think this is working as intended. That version number only gets updated when incompatible changes to the project file data are introduced that requires a data migration and 4.0.1 didn't modify the project file structure in a way that was incompatible with 4.0.0.

As much as possible I try to avoid changing the project files during patch releases (incrementing the last number in the version) so they are safer to update to, they'll mostly just be bug fixes.

I'm sure when 4.1.0 is ready the project file will change again. In fact I'm currently working on making it so projects are stored in multiple files rather than just a single `.gbsproj`, making it easier for teams to work on a project collaboratively, that will definitely need a big migration!

**Comment by maxoakland** [comment]
>In fact I'm currently working on making it so projects are stored in multiple files rather than just a single `.gbsproj`, making it easier for teams to work on a project collaboratively, that will definitely need a big migration!

That's amazing news

**Comment by mxashlynn** [comment]
Thank you, I thought it might be a misunderstanding on my end.

And I deeply appreciate your splitting the project file into multiple files -- that's wonderful!  😄
