### ISSUE TITLE
[Request] Multiple choice with more than 2 choices

### ISSUE THREAD

**Issue by sittingrisk** [chrismaltby/gb-studio#158]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

It would be really useful to have a multiple choice tool that allows for more than two options. As it is now multiple choice sets a variable to true if option A is chosen and false if option B is chosen. Maybe if there are more choices than true then each choice could set a different variable to true and a variable for all other choices to false.

**Comment by chrismaltby** [comment]
I'd been thinking about this one for a while, and will probably look at this after the next release. I'm thinking rather than setting multiple variables like you suggest it would just set the value of a variable to a different number based on the option chosen (so variable would be "0" if the first option is chosen, "1" if the second option, "2" if the third option etc. I think you should also be able to have more options than fit into the box, in which case it will show pagination on the bottom right. Finally I think it's a good idea to have an alternate view where the menu appears on the bottom right of the screen which will allow people to do menus which has been requested a lot.

Rough mock of UI below:
<img width="757" alt="Screen Shot 2019-05-14 at 9 41 37 AM" src="https://user-images.githubusercontent.com/16776042/57683867-8136c680-762c-11e9-8e91-43557c1d6348.png">

**Comment by KitF** [comment]
Would it be possible to have "B" cancel out of a multiple choice? Or would we always need to include a "Cancel" option?

**Comment by thomas-alrek** [comment]
In most GB games the convention when pressing B in a multiple choice dialog is to select the "negative" option. So if the options are "Yes" and "No", B would usually select "No", not cancel it

**Comment by chrismaltby** [comment]
I think making it work like the following should be okay, and also allow the event to be backwards compatible with everyone who's used it previously (this is going to be quite important but also difficult as features are added/modified going forwards)
<img width="896" alt="Screen Shot 2019-05-15 at 10 23 58 AM" src="https://user-images.githubusercontent.com/16776042/57764566-9c243c00-76fb-11e9-8e97-47f4bc241eea.png">
So the last option always returns 0/false as that is the cancel choice, but you can have as many options before that as you want and they will set the variable to a different value based on which option you chose. B button will automatically select the last option, but you can optionally hide the last option.

That way if you wanted to make a menu but didn't want close to be the last option you could hide it but B button would still close the menu. Or if you wanted a multiple choice with two positive options and B to cancel you could make Choice A and Choice B and hide the cancel option.

**Comment by chrismaltby** [comment]
In commit 8ba7180f841f009f1a9884ebd4342c8828901d20 I've made it so pressing B sets the cancel option. Multiple choice with more than 2 options will probably be implemented later working as described above

**Comment by timsamoff** [comment]
What about 4 options like this?
<img src="https://user-images.githubusercontent.com/62411/57795017-d2f95280-76f9-11e9-9cc6-2d5bcc2d6a6e.jpg" width="250">
Where the pointer wraps back to 1 after 4.

This could also support pagination, with 4 more options on each new page, although, imho, games like this shouldn't have more than one page of options.

**Comment by darkhog** [comment]
I think we should generalize the multiple-choice menu and make it fit to the longest option, in the vertical layout. Then, allow user to set position where the menu would open (which also would allow to display text box and the menu at the same time). That way, we could make Pokemon-style menu with just that command.

**Comment by KitF** [comment]
I'd love the options, 4 isn't a lot of options for a menu.

**Comment by pau-tomas** [comment]
I worked on a [DRAFT patch](https://github.com/pau-tomas/gb-studio/commit/1dd7bc2315972c9eea6d42a9827b5de39f764e9b) for a `Menu event` that covers the vertical layout case. It's dependent on the conditional changes introduced on the `Case Event` branch so right now isn't a clean merge with `develop` but it's pretty much functional.

I allows to render up to 8 options with 6 characters max each. 

To me, it feels more natural that selection an options sets the variable to a value between 1 and 8, while cancelling (by pressing `B`) sets it to 0. That's why I opted to implement a separate event instead of reusing the `Choice` one. 

Some screenshots:

<img width="326" alt="Screenshot 2019-09-14 at 13 00 09" src="https://user-images.githubusercontent.com/54246642/64907878-551d7600-d6f0-11e9-9c35-de48faecedbb.png">
<img width="592" alt="Screenshot 2019-09-14 at 12 59 58" src="https://user-images.githubusercontent.com/54246642/64907879-551d7600-d6f0-11e9-9eb7-1539e0a6cd18.png">

**Comment by pau-tomas** [comment]
Did a bit of tweaking on my Menu code to support up to 8 options, with the last one optionally being _Cancel_ and setting the variable to `0` or a normal option and setting the variable to `8`, making it compatible with the current `Choice` Event.

This is what I came out with:

*8 options, with values from 1 to 8*
<img width="357" alt="image" src="https://user-images.githubusercontent.com/54246642/66878412-bd79a480-ef87-11e9-8e4d-4a30efe44618.png">

*8 options, with values from 1 to 7 and then 0*
<img width="361" alt="image" src="https://user-images.githubusercontent.com/54246642/66878419-c8ccd000-ef87-11e9-9c7e-549e77764032.png">

*2 options, with values 1 and 0 (same as the current `Choice`)*
<img width="361" alt="image" src="https://user-images.githubusercontent.com/54246642/66878432-d84c1900-ef87-11e9-888a-5b72767b7b19.png">
