### ISSUE TITLE
Close Dialog Through Script

### ISSUE THREAD

**Issue by morganwalkup** [chrismaltby/gb-studio#200]
**Is your feature request related to a problem? Please describe.**

Currently, there is only way to advance dialogue. The player must press "A".
This limitation prevents the dialogue box from being a more useful, general-purpose tool.

**Describe the solution you'd like**

A new script event should be added to advance to the next piece of dialogue. It could be as simple as "Close Dialogue".

**Describe alternatives you've considered**

We could open this up even further by allowing player inputs to be simulated and triggered through script events. In that case, we could close the dialogue by simulating an "A" press.

**Additional context**

Programmatic control of the dialogue box opens up a lot of possibilities for dynamic content! I'm experimenting with animation in the dialogue box by combining instant animation speed with a custom ascii.png.

**Comment by RichardULZ** [comment]
I've thought about this recently too.
The implementation i can think of that would work with our code, 
Some kind of tick box for "Continue script", it wouldn't automatically close, but you could close it with move overlay, or a delay + new text.

**Comment by RichardULZ** [comment]
Less related, but this may be helpful for you, i only just finished it.
UI Ascii table characters list, that you can copy paste from. 
https://gist.github.com/RichardULZ/2920dca52989902dbb7225318256c545

**Comment by timsamoff** [comment]
> I've thought about this recently too.
> The implementation i can think of that would work with our code,
> Some kind of tick box for "Continue script", it wouldn't automatically close, but you could close it with move overlay, or a delay + new text.

I feel like this would need some sort of Wait function, though. It would be nice to be able to trigger dialog, add a Wait, and then either add a "Close dialog" Event or add a new dialog Event.

**Comment by RichardULZ** [comment]
@timsamoff Thats what i meant, said delay instead of wait.

Currently, a text box in code says "script continue = false", every time, so it can pause the script, and start checking if you've pressed A to close it.

If you change this to say  "script continue true", it will start writing and showing text, but then keep running the next script events, without closing the text box.

You can then use normal "wait" events, 
"close dialogue" is the same code as "overlay move to" (it could be duplicated with a new name),
new dialogue would function as expected, and any other existing function you can think of would work too.

**Comment by MorganWalkup** [comment]
@RichardULZ Adding a "continue script" option sounds like a great idea to me.

Just to clarify, I would expect a script like this:
```
1. Display Dialogue "Text 1" (continue script)
2. Wait 5.0s
3. Display Dialogue "Text 2" (continue script)
...
```
to ignore all user input during the "Wait 5.0s", and only display "Text 2" when the 5.0s is over.
Is that what you had in mind?

--
Also, I didn't realize that the dialogue box is using the overlay internally. Does that mean we could potentially do full-screen dialogue boxes, or put dynamic content in an overlay? That might be worth another feature request.

**Comment by MorganWalkup** [comment]
@RichardULZ Any updates on this? Let me know if I can help out.

**Comment by RichardULZ** [comment]
Messed about with it for a few hours today, something i'm doing is causing some text boxes to corrupt, but re creating them fixes it, so i'm rethinking my strategy. 
Also, having the Continue Script tick box takes up space that otherwise makes the engine simple and clean.
Might putter about with a separate event as Continue next script, or Continue all scripts / Don't Continue all scripts.
Keep in mind messing with this stuff get's janky pretty quick. Later though, bed time.

**Comment by N47h** [comment]
**Here's what I posted as a separate issue, before realizing this one existed:**

> It would be nice to have dialogue that goes away automatically after a specified amount of time, rather than waiting for input.
> 
> I personally hope to use this with a timer of 0, so I can continue the script immediately, with the dialogue kept visible by the overlay.

I think a "Timed Dialogue" event would be a fairly elegant method with more versatility, and there wouldn't be a need for a separate event to get rid of it.
