### ISSUE TITLE
[Bug] "Variables: Add Flags" does not function when using windows10

### ISSUE THREAD

**Issue by locherunderscore** [chrismaltby/gb-studio#281]
The following script function:
"Variables: Add Flags"
does not work when using gbstudio on windows10.

No values are changed and when outputted via dialog box, the result is always 0.

[Set Flags] will successfully set the flags and [Clear Flags] successfully clears flags.
I want to ask if you could look into how [Add Flags] is implemented in order to find out why this script function is compiled successfully on Macs and is wholely ignored for windows 10 pcs.

**Comment by pau-tomas** [comment]
Here's a simple project to test the case. [bitwise_sample.zip](https://github.com/chrismaltby/gb-studio/files/3563804/bitwise_sample.zip)

The expected behavior would be for the `$01$` variable to alternate between `0` and `1` everytime you talk with the Sage actor.

On Windows 10 (from @LocherGit tests) the value is always `0`.

@chrismaltby I don't have a Windows 10 machine to test, but I'll try to do some investigation.

**Comment by locherunderscore** [comment]
I closed this due to the merge request resolving my issue.
At least the expected behavior was observed on my win10 computer.
