### ISSUE TITLE
Error when running or exporting project (missing file on appdata)

### ISSUE THREAD

**Issue by diguifi** [chrismaltby/gb-studio#35]
I created a project containing the default sample project, and didn't change a thing.
When attempted to run or export (web or ROM) I got this error:  
`... \AppData\Local\Temp/_gbs/gbdk/lib/small/asxxxx/gb/cr.: cannot open. 4294967295`

I searched for this file and it is not there (also ran the .exe as admin, got the same).

**OS:** Windows 10 pro x64
**Processor:** Intel Core i5-7500T

_(btw, this project is amazing, congrats!)_

**Comment by diguifi** [comment]
The full path is
`C:\Users\Desenvolvimento\AppData\Local\Temp\_gbs\gbdk\lib\small\asxxxx\gb`

It worked fine when using `%localappdata%\Temp\_gbs\gbdk\lib\small\asxxxx\gb`

**Comment by chrismaltby** [comment]
I think it's an issue with [gbdk](http://gbdk.sourceforge.net/), the application I'm using to compile the ROM file (the last official Windows version is from August 2000) and from what I can tell the Windows version isn't allowing filenames over what looks like 76 characters. The Mac and Linux versions seemed to get a few more years of updates and are generally a bit more stable. Going to request for help if anyone has any suggestions where I could get a more up to date version for Windows (it's possible someone forked it and I've missed it).

As an alternative, I could make it try an alternate folder if it fails (say maybe `C:\GBStudioTools`) and I can provide a zip so that you can manually place the build tools in a location with a short path name. Not being a Windows user myself, could you maybe suggest a location where people aren't going to be too annoyed about these files going (that also would have a short filename) or do you think `C:\GBStudioTools` would work?

**Comment by diguifi** [comment]
_"where people aren't going to be too annoyed about these files going"_

I personally don't care at all for it going directly at `C:`, but maybe people rather it on `C:\Program Files\GBStudioTools`

**Comment by MajkelKorczak** [comment]
I've found a fork of gbdk used by users from retro forums: [https://github.com/andreasjhkarlsson/gbdk-n](url)

**Comment by ISSOtm** [comment]
That fork cannot handle banking, which considering the bloated code size produced by SDCC (the back-end compiler), is particularly crippling.

**Comment by chrismaltby** [comment]
I believe this issue is now fixed in the current dev builds and also [the 1.1.1 release](https://chrismaltby.itch.io/gb-studio) (only on Itch.io right now)
