### ISSUE TITLE
Command Encapsulation

### ISSUE THREAD

**Issue by josefnpat** [chrismaltby/gb-studio#37]
I find myself repeating a lot of code over and over, and was thinking it would be nice to be able to make our own "functions" in the UI.

Let's say I have four sprites that I'm using for one, and I want them to all appear or disappear at the same time. Right now I have to use 4x hide actors.

What would be nice is if I could define my own block, and just run that to hide all four actors, and reuse it later.

**Comment by RichardULZ** [comment]
Is this for editor visibility & Copy Paste sake, Like a **Folder**?

Making something out of the IF blocks might be a good starting point for developers, the else section is already collapsible, and copying the IF block will include its contents!

I would love script functions that have their own tab, with an event to jump to a script/function, but it could cause issues since Actor Specific commands are Scene Specific, except player.

Current workaround for **copying multiple blocks**,
Put them in an IF statement, copy that block, then paste it where you need.
