### ISSUE TITLE
The colors don't match

### ISSUE THREAD

**Issue by SENDIXXX** [chrismaltby/gb-studio#480]
![segnala](https://user-images.githubusercontent.com/70237298/91314709-255b6700-e7b7-11ea-840a-010c1ef1b76f.PNG)
As you can see from the image if I use sprites with the palettes they don't match then when I start the game I don't know why do you recommend?

**Comment by chrismaltby** [comment]
Hi @SENDIXXX I think you've found a bug in how I'm previewing the sprites in the editor

In the engine I'm doing the following
`#e0f8cf` = 1st color in palette
`#86c06c` = 2nd color in palette
`#306850` = 3rd color in palette
`#071821` = 4th color in palette

but actually in game it is 
`#e0f8cf` = 1st color in palette
`#86c06c` = 2nd color in palette
`#306850` = **4th color in palette**
`#071821` = 4th color in palette

it's not possible to use more than 3 colors/shades for a sprite (because the 4th color is transparency) so the mid grey one gets merged with the darkest one

e.g this first sprite would appear incorrect in editor compared to in game
![dog-broken](https://user-images.githubusercontent.com/16776042/91334497-f77e1e80-e7c6-11ea-9f52-278a4e52d66a.png)
but the second one here works
![dog](https://user-images.githubusercontent.com/16776042/91334500-f816b500-e7c6-11ea-8f82-20b71e328340.png)

you just need to replace the `#306850` in your sprite with `#86c06c`

I'll update the UI to make sure it matches how sprites look ingame

**Comment by SENDIXXX** [comment]
so i can only use 3 colors for my actors?

**Comment by SENDIXXX** [comment]
@chrismaltby so i can only use 3 colors for my actors?

**Comment by chrismaltby** [comment]
Yeah, unfortunately that's correct. The Game Boy Color only allows three colors per sprite

**Comment by chrismaltby** [comment]
I've updated the sprite preview rendering to correctly match the ingame sprites in #491 The next beta will have this fix in place

**Comment by benjaminlewin** [comment]
I'm currently experiencing this with an original GB game project for GB Studio 3.2.1. It doesn't seem to just be a limit to the number of colors present in the sprite but seems to just affect the 3rd color (#306850). I have a sprite that consists of the 4th color (#071821), the 3rd (#306850), and transparency (3 colors total), and my sprite still shows up as the 3rd color being merged as the 4th color. It appears this way in the Frame Canvas in the Sprite Editor as well as in the scene of the game itself. Please advise.

**Comment by maxoakland** [comment]
> I'm currently experiencing this with an original GB game project for GB Studio 3.2.1. It doesn't seem to just be a limit to the number of colors present in the sprite but seems to just affect the 3rd color (#306850). I have a sprite that consists of the 4th color (#071821), the 3rd (#306850), and transparency (3 colors total), and my sprite still shows up as the 3rd color being merged as the 4th color. It appears this way in the Frame Canvas in the Sprite Editor as well as in the scene of the game itself. Please advise.

The third color isn't allowed on sprites. If it's a DMG game you can make it show the 2nd color as the third color using the B&W palette option but it only works on DMG-mode games
