### ISSUE TITLE
Improve error message when background images aren't valid (currently not clear)

### ISSUE THREAD

**Issue by Regalleigh** [chrismaltby/gb-studio#51]
initialization error keeps happening when trying to run or export the game. 
[the plantation2.zip](https://github.com/chrismaltby/gb-studio/files/3113868/the.plantation2.zip)

**Comment by chrismaltby** [comment]
Hi Regalleigh, this was your issue:

<img width="1019" alt="Screenshot 2019-04-24 at 21 09 19" src="https://user-images.githubusercontent.com/16776042/56690424-51ec0400-66d5-11e9-93af-54b4180aa222.png">
The image was 162px by 145px but it needed to be 160px by 144px

https://www.gbstudio.dev/docs/backgrounds/
> Backgrounds are divided into 8px x 8px tilesets so the total image size must be a multiple of 8px in both width and height. A background has a minimum size of 160px x 144px (the screen size) and currently a background can be no larger than 256px x 256px.

I've cropped your image and it's working as expected now.

![titlescreen](https://user-images.githubusercontent.com/16776042/56690573-ae4f2380-66d5-11e9-903a-0cef863dc6f4.png)

<img width="328" alt="Screenshot 2019-04-24 at 21 12 46" src="https://user-images.githubusercontent.com/16776042/56690594-beff9980-66d5-11e9-9e14-c70b57b7c2b8.png">

I'm going to leave this issue open though as this error should be handled much better. Maybe the scene should show an error overlay. And also the backgrounds section should show an error too.

**Comment by chrismaltby** [comment]
Fixed in develop commit e1b22b4c84932dfcf3b1c1d09d566890c97fa98e now images that are invalid sizes will actually work (but will automatically be cropped from top left if too large)
If you view images that don't match the specifications you'll now see warnings in the Backgrounds section like the following

![Screen Shot 2019-04-26 at 5 19 35 PM](https://user-images.githubusercontent.com/16776042/56821944-8bdd1780-6847-11e9-8f55-96a3961a0919.png)
