### ISSUE TITLE
ChunkLoadError v2Beta f1a9c878 failing on rom build

### ISSUE THREAD

**Issue by RichardULZ** [chrismaltby/gb-studio#535]
**Describe the bug**
When building game with v2beta prebuilt (not from source):
```
ChunkLoadError: Loading chunk 4 failed.
(error: file:///E:/Downloads/GB%20Studio-win32-x64/resources/app.asar/.webpack/renderer/main_window/vendor-lodash/index.js)
```

**To Reproduce**
1. Download v2Beta development build from github (tested windows 64 bit)
2. Open or create project
3. Build rom

**Expected behavior**
Actually build, This issue is high priority, possibly from the typescript refactor?

**Screenshots**
![image](https://user-images.githubusercontent.com/34431457/93039421-892ccd80-f69b-11ea-982a-aec6a80eb4e0.png)

**Platform (please complete the following information):**
 - OS: Windows 10 64bit
 - App version 2.0beta dev f1a9c878 

**Additional context**
2 additional cases reported on discord (thanks skittles for being brave) https://discord.com/channels/554713715442712616/570925559346102273/754874965647556658

**Comment by chanunnaki** [comment]
Can confirm, just experienced the same issue on Mac, Mojave.

**Comment by RichardULZ** [comment]
https://medium.com/@botfather/react-loading-chunk-failed-error-88d0bb75b406
Might help?

**Comment by chrismaltby** [comment]
I'm seeing the same. It's weird, looks like it's trying to find lodash in `.webpack/renderer/main_window/vendor-lodash` rather than where it's located one folder back in `.webpack/renderer/vendor-lodash`.

<img width="612" alt="Screenshot 2020-09-14 at 17 11 13" src="https://user-images.githubusercontent.com/16776042/93110542-60adcf00-f6ad-11ea-9f18-09f71c4ce839.png">

I think it's something to do with the webpack code splitting in the build game middleware to only load the compiler code when you first run your project (so it can load quicker)

```
      const buildProject = await import(
        "../../../lib/compiler/buildProject"
      ).then((module) => module.default);
```

I've not really changed much about that from the previous build other than the middleware is now a Typescript file, I'll try rolling back to different commits locally and see if I can pinpoint when the issue was introduced.

**Comment by patrickmollohan** [comment]
Can confirm the same thing happens on Ubuntu. However, downloading the source and running via "npm run start" works perfectly.

**Comment by chrismaltby** [comment]
I've just pushed an update that is fixing this for me based off this Stack Overflow answer https://stackoverflow.com/a/60531888

It was a one line config change to `tsconfig.json`...
1e94a45e0962721487fb1b369c5dafe779032a92

The github built versions are working for me on Mac and Windows 64-bit with this change.

**Comment by chanunnaki** [comment]
Tested 1e94a45e, it's building properly now. Nice!
