### ISSUE TITLE
[Request] Way to display Variable values in Display Text

### ISSUE THREAD

**Issue by jrmysrss** [chrismaltby/gb-studio#54]
Instead of using "If Variable..." and scripting out each possible scenario to have the "Display Text" say something specific, it would be nice to be able to place a Variable in the "Display Text" value so when the text appears on screen it shows the variables value.

Examples for could be a way to have the players name appear in the dialogue  "Hello [[PlayerName]]!" or could be used to see how much of "X" item the player has on them "You have [[GoldAmount]] gold!".

**Comment by chrismaltby** [comment]
Implemented this in develop commit 4bc17c4169663e9bde372488c3671fa96c6f7390. Rather than using an identifier like [[PlayerName]] you need to use the variable's id which is now given next to the variable name in the drop downs.

<img width="296" alt="Screenshot 2019-04-28 at 21 35 38" src="https://user-images.githubusercontent.com/16776042/56869844-17000e00-69fe-11e9-91c9-ef6657578593.png">

You can then use the id in the "Display Text" event like follows:

<img width="298" alt="Screenshot 2019-04-28 at 21 37 00" src="https://user-images.githubusercontent.com/16776042/56869849-23846680-69fe-11e9-9a09-37c7ab14076d.png">

which will appear in the game as

<img width="480" alt="Screenshot 2019-04-28 at 21 37 19" src="https://user-images.githubusercontent.com/16776042/56869856-38f99080-69fe-11e9-93fe-fdd584bdc69e.png">

Only the first 100 variables have these ids so you would you can use from $00$ to $99$

**Comment by jrmysrss** [comment]
Beautiful! Can't wait to use it!
