### ISSUE TITLE
Use monospace font for editor dialog boxes

### ISSUE THREAD

**Issue by DeerTears** [chrismaltby/gb-studio#602]
**Is your feature request related to a problem? Please describe.**
Typing dialog into the GB Studio editor uses a normal dynamically-spaced font, but GB Studio games are limited to display 18 characters on a line at once, with the last line being limited to 17. For most dialog this isn't an issue, but this presents a problem for lining up ASCII art and alternate-spacings of text like going right-justified, or adding indented spaces to a line.

![image](https://user-images.githubusercontent.com/47726614/95635876-8460fc80-0a42-11eb-9ed0-2574586d951c.png)
(I tried doing more # characters to show how this doesn't scale-up nicely but that actually produced a different rendering bug which I'll submit an issue for as well)

Although it's pretty clear that lines cannot continue because of a character limit, a monospace-width font would help illustrate other limitations such as the last line being 1 character fewer than the rest,
![image](https://user-images.githubusercontent.com/47726614/95631840-3abfe400-0a39-11eb-823a-749edcc6830a.png)

![image](https://user-images.githubusercontent.com/47726614/95631880-4e6b4a80-0a39-11eb-970f-5170d248fbf7.png)
![image](https://user-images.githubusercontent.com/47726614/95631993-91c5b900-0a39-11eb-8d57-1495899dfa95.png)

**Describe the solution you'd like**
Use a monospace-width font in dialog boxes so it's clear where character limits will appear.

**Describe alternatives you've considered**
We could always continue to use standard spaced fonts instead.

**Comment by chrismaltby** [comment]
Thanks @DeerTears I'm sure it did actually used to be a monospace font, I'll sort this out.

The other thing I'd also considered doing at some point is having a floating preview of the actual ingame dialog box showing the font/frame/avatar that you're using so you'll see exactly how content is aligned. When the text field has focus this overlay would appear to the side showing a preview in the in game style

<img width="493" alt="Screenshot 2020-10-10 at 11 05 30" src="https://user-images.githubusercontent.com/16776042/95652435-cc3a5f00-0ae8-11eb-94fa-23f5a3135380.png">

Not sure when I'll get time to implement this though so switching the font to monospace is a quick win.

I think the other bug you spotted is actually fixed in the latest dev builds, beta4 should have that one fixed
