### ISSUE TITLE
Project won't save once the file size reaches ~520 MB

### ISSUE THREAD

**Issue by FranticPedantic** [chrismaltby/gb-studio#631]
**Describe the bug**
When the size of the project file surpasses about 520 MB, the project no longer saves. The program becomes slow and unresponsive and it takes a long time for the UI to respond when doing things like adding text to dialogue boxes.

**To Reproduce**
Keep creating (copying, pasting) programming blocks/commands and saving.

**Expected behavior**
The program should keep working and allowing the project to be saved.

**Platform (please complete the following information):**
Windows 2.0.0-beta2

**Additional context**
The logic that handles the player's attacks and abilities for my game needs to be copied and pasted into every single scene. This adds 3 MB of data for each scene. I have optimized the programming as much as possible but due to this issue, I am unable to complete my project.

**Comment by DeerTears** [comment]
Just so you know, beta4 is available. I can't guarantee that upgrading will fix the lag, but beta4 should give you more script options for your case of copying multiple scripts around. You should be able to check a box that says "persist between scenes" for a script so you don't need to copy/paste it every time, and that options should give you lots of in-game and in-editor performance.

If trying that doesn't work, would you mind including your project as a .zip file here? If it's causing editor slowdown it'd be really useful to see this in action, since I've never heard of a project freezing the editor, even when there's countless scenes and scripts involved.

**Comment by me13** [comment]
wait how did I not know beta4 is out

**Comment by me13** [comment]
wait what
