### ISSUE TITLE
Seeing error when attempting to run game

### ISSUE THREAD

**Issue by nichangell** [chrismaltby/gb-studio#643]
<img width="1241" alt="Screenshot 2020-11-03 at 10 14 19" src="https://user-images.githubusercontent.com/73882712/97973400-e7358180-1dbd-11eb-9300-a2971cbff9a0.png">
Hi,
I see this error when I attempt to run my game to test it. Very new to all of this so don't know what it means, can you help?
It was running fine and I changed nothing and now suddenly I'm getting this error message.
thanks,
Nich

**Comment by RichardULZ** [comment]
Please remember to follow the issue templates, and note your operating system and version of gb studio, It seems you might have bypassed the "Bug/feature" template option somehow, since it's not tagged as a bug either...

The error message is saying permission denied for one of the build processes, not sure if there's an equivalent to run as admin on mac.
The /var/folders seems to be the temporary location, this sometimes clears from just rebooting the mac, so give that a shot first.

**Comment by pau-tomas** [comment]
You can also try removing the `_gbstools` folder mentioned in the error and rebuild.

**Comment by gmarty** [comment]
I had the same error yesterday. I switched the project and reopened it. I didn't even had to restart GB Studio.
I also emptied the build cache before closing the project, but I'm not sure if that was needed or not.

**Comment by nichangell** [comment]
Thanks everyone. Rebooting totally solved it! (Will make sure to follow issue templates in future too!)

**Comment by RichardULZ** [comment]
Awesome, hope it helps other mac osx users that cant run or build the game, running into this Permission denied error.

You can close this issue now @nichangell
