### ISSUE TITLE
(Request) Allow changing the interact Button for each scene-type

### ISSUE THREAD

**Issue by DeerTears** [chrismaltby/gb-studio#648]
**Is your feature request related to a problem? Please describe.**
People like changing around their control scheme. gmarty has created a pull request that swaps the run and jump buttons for platformer mode to fit with games like Super Mario Land 2 #646 , but the interact button is independent from the run and jump buttons. Changing these platformer buttons calls into question how the "interact" button should be handled.

I see 1 of 4 possible outcomes that could all be desired from changing around the interact buttons:

### 1/4: Interact is tied to run
Benefits: Players won't talk to actors by accident when they jump.
Drawbacks: Any scripts associated with "A" in non-platformer types need to be removed and re-attached for any platformer scenes, and there is no (clear) way to determine scene type through scripts.

This situation is what I want to prevent if we decide to swap (or allow swapping) the platformer buttons.

### 2/4: Interact is tied to jump
Benefits: "A" is reliably the "interact" button in a SML2-style button layout. Desirable for games without jumping.
Drawbacks: Players are stopped from jumping if they interact with an actor by accident.

### 3/4: Interact is tied to start or select
Benefits: No button conflicts.
Drawbacks: Non-standard.

### 4/4: Interact is tied to up or down
Benefits: Games without ladders can incorporate kirby-style doors. Games with ladders could include a proximity check on ladders for more complicated ladder gameplay.
Drawbacks: Crosses over functionality with ladders, may cause other unintended issues?

**Describe the solution you'd like**
Expose the button used for hit_actor in Platformer (and perhaps other scene types) as an option in the Settings menu.

![image](https://user-images.githubusercontent.com/47726614/98410595-d5581680-2029-11eb-8833-d045d36c9f48.png)
This but with the above buttons mentioned. A "reset to default" button would also be nice for each scene type.

Here's the bit of code that needs to be exposed to the editor: `INPUT_A_PRESSED`
In this section of Platformer.c:
```C
if (grounded && INPUT_A_PRESSED) {
    if (player.dir.x == 1) {
      hit_actor = ActorAtTile(tile_x + 2, tile_y, TRUE);
    } else {
      hit_actor = ActorAtTile(tile_x - 1, tile_y, TRUE);
    }
    if (hit_actor && (hit_actor != NO_ACTOR_COLLISON)) {
      ScriptStart(&actors[hit_actor].events_ptr);
    }
  }
```

**Describe alternatives you've considered**
Swapping the jump button / interact button can technically be done through "Attach Script to Button" but it's not immediately apparent that this event can swap button functionality in an unintended way.

**Additional context**

**Comment by chrismaltby** [comment]
Thanks @DeerTears for this detailed break down of all the different options here. I've been doing a bit of testing out different games to see what the precedent is, the hope is this could just be fixed with a sensible default value.

So far most of the platform games I'm trying either don't have an interact button or those that do mostly use `Up`. We could do that (and I'd actually considered it pre releasing the first beta) but then it would be inconsistent with the other scene types.

I'm not completely against making this configurable but we just need to be careful as replacing those hard coded values with anything dynamic can both affect performance and make the code more difficult to maintain.

As an alternative maybe we could do this:
- Like in #646 switch B & A on Platform scenes so B is Run and A is Jump (matching most platform games on the Game Boy) 
- Make Up the default interact button for Platform scenes
- Add a new event "Action: Player Interact" which when combined with "Attach Script to Button" would allow replacing either "B" if you don't want to allow running, or "A" if you don't want to allow jumping (or I guess Down if you wanted also) with the interact action

I'll continue to have a think about what to do here but it's definitely a tricky one to get right.

**Comment by DeerTears** [comment]
We got this now \o/ ty
