### ISSUE TITLE
Request to add more documentation on "collision groups" and "On Update"

### ISSUE THREAD

**Issue by PixelShift-gb** [chrismaltby/gb-studio#659]
I searched the documentation and couldnt find any information on collision groups in the actor event, also couldnt find details for "on update" for actor trigger events.

![COLLISIONS](https://user-images.githubusercontent.com/2074620/99012030-77409d00-251b-11eb-854d-3a3d66456be4.png)

**Comment by RichardULZ** [comment]
Documentation for 2.0 beta is very incomplete, the beta docs are live at https://develop.gbstudio.dev/ but many pages are not changed, partially because changes and bug fixes are being prioritized first.
There is a documentation channel on discord for anyone to discus / help with the docs, and the live site github 
https://github.com/chrismaltby/gb-studio-site
