### ISSUE TITLE
"Joypad Input : Attach Script to Button" avoid character moving when switching scene

### ISSUE THREAD

**Issue by dnvldn** [chrismaltby/gb-studio#684]
**The bug**
When switching in a scene where i use "Attach Script to Button" on the arrow key then switch back to a regular scene, I can't move my character using those arrow keys. The script attacher to the arrow keys doesn't persist, i juste can't move anymore...

**To reproduce**
Download this project to see the bug : [bug demonstration.zip](https://github.com/chrismaltby/gb-studio/files/5660166/bug.demonstration.zip)

**Expected behavior**
The character should be able to move when switching back to the first scene

**Platform**
OS: Windows 10 x64
App version: GB Studio 2.0.0 Beta 4 for Windows 64-bit

**Comment by pythonmcpi** [comment]
Same thing happens for me, I'm also on the 4th beta and using Windows x64. This bug occurs in the Sample game as well, after the space flight (shooting enemies) it will not be possible to interact with anything until you restart the game (and it's not possible to save the game before restarting either, since you cannot interact)

**Comment by pau-tomas** [comment]
This should be fixed by #620 and is available in the [Beta Development builds](https://github.com/chrismaltby/gb-studio/tree/v2beta#beta-builds)
