### ISSUE TITLE
On Hit Player Group

### ISSUE THREAD

**Issue by sfernandez131** [chrismaltby/gb-studio#698]
When Collison Group 1 is active the first On Hit event goes into an infinite loop or will loop some number of times, it's odd. If you hold down a direction that will move you away you can escape the loop but it's one frame at a time. 

1. Set actor in scene. 
2. Set collision group 1 on actor.
3. Add some event for the player to experience if the collision is with player.
4. Collide with actor.

I expect the event or events to play out in order as they usually would.

**Platform (please complete the following information):**
 - OS: Windows 10
 - App versionV2-beta4

**Comment by RichardULZ** [comment]
Please be more specific about the event used, or a screenshot may help, dialogues will likely have issues (noted in other bug reports).
The transition to Cutscene (init, interact, trigger) and simultaneous (update, hit, attach to button/timer) scripts in 2.0 makes these problems more apparent.

Hit events fire about 2-4 times a second, not every frame for performance.
This is required to keep taking damage from an actor / running into the actor again after it moves.

A work around for your case would be checking if variable false on hit, setting it to true, then doing your script and waiting, before setting it to false again. in the Else section, use a Stop Script event so it will early out if not enough time has passed since last collision.

**Comment by sfernandez131** [comment]
That solution worked perfectly! I can't believe I didn't do that. I'm using a similar trick in other areas. Thank you!
