### ISSUE TITLE
Sprite transparency clashing

### ISSUE THREAD

**Issue by Level0gamedev** [chrismaltby/gb-studio#7]
![test](https://user-images.githubusercontent.com/20285394/56464340-cca2df80-63b4-11e9-8a8d-6ac3eeb4cc2e.gif)
If player and another sprite are overlapping while moving the player the overlapped sprite is showing through the player (possibly only on each other frame, not 100% sure). See attached gif

- I am using the gb studio on windows10, the issue occurs in the example project.
- The issue was noticed during preview, not sure if the issue persists in built projects, .gb or .html.

**Comment by chrismaltby** [comment]
That's actually a limitation of the Game Boy hardware itself I believe, the original Game Boy has no ability to control z-index order of sprites, and instead uses the X Coordinate of the sprites to determine the draw order. The alternative would be to make it so no actors can overlap but I tried it that way too and prefer it as is (also you need to check less tiles on the collision detection which was starting to be a problem). Don't think I can do much about this one sorry.

**Comment by Level0gamedev** [comment]
If we can't always draw the player last, then an alternative solution might be to lock the player to tile grid - maybe make that an option for the project?

By locking player to tile is to make sure that player always ends up on a grid. So if I press left for one frame I shouldn't move just one pixel to the left, but move one tile (pokemon does that, don't remember if the gb zeldas do that, but it was pretty common in games from that time). This would eliminate the need for checking for extra sprite tiles. 

Now thinking about it, this would only fix the issue if we would also be able to choose if the whole sprite is solid, and not only the bottom two tiles. So, maybe not really a fix.

Nevertheless, would love the ability to make sprites stick to tile grid.

**Comment by pinobatch** [comment]
There are other possible workarounds that involve partial software rendering, and I don't know precisely how feasible they'd be because of the CPU overhead of software bit shifting. You might end up having to cut the frame rate on DMG to 30 fps.

- Horizontally shift any sprite that's in front of another sprite so that they're 8-pixel aligned. For sprites with the same X coordinate, Z-order works as expected: lower OAM index in front.
- Allocate new background tiles for any sprite that's occluded and draw it to the background, as seen in _Prehistorik Man_.

This Z-order quirk is not an issue for Game Boy Color software.

**Comment by chrismaltby** [comment]
The latest dev builds now have the option to use a custom color palette which outputs the game as a Game Boy Color ROM instead, as @pinobatch says this issue doesn't occur there so one option is to enable a custom palette (you can leave the colors as defaults or change them whichever you prefer)
