### ISSUE TITLE
[Proposal] Custom file extension

### ISSUE THREAD

**Issue by thomas-alrek** [chrismaltby/gb-studio#71]
My proposal is that GB Studio saves the json files as a different extension e.g, `.gbproj`.
This way, the application could register the extension (at least on macOS), and it would be possible to implement a "Open with GB Studio" functionality

**Comment by DerekLF** [comment]
This would also work on Windows. When you launch the 'unknown' file it will ask what program you want to use to launch it. And if you want to use it with all these file types.

**Comment by thomas-alrek** [comment]
Yeah that would work. I guess on Windows, you would have to update a registry setting to automate it?

**Comment by DerekLF** [comment]
![image](https://user-images.githubusercontent.com/39482719/56827104-2b0d0980-685e-11e9-82de-c61709f5250d.png)
By opening an unkown file type you'll get a menu just like this. and you'll have to locate the GBstudio.exe and it will always open this file type with GBstudio(if you check that box on the bottom)

**Comment by chrismaltby** [comment]
I'm going with `.gbsproj` rather than `.gbproj` (because GarageBand already took it!) but commit 27fc5e8b57696019407288c0edebf2a5e06ab457 adds support for this in the macOS build. It will only work with the version built for distributing so you need to `npm run make` and open the version in the `out` folder.

I also changed the naming on new projects so instead of `project.json` it's `The Name Of Your Game.gbsproj`. Kept compatibility with `.json` files though so old projects will still open.

I believe the Electron event app.on("open-file") only fires on macOS so there's a little bit needed to make this work on Windows, sounds like you use `process.argv` instead but not sure yet how you handle opening a file while the app is already open, need a bit of time by Windows machine to test.

This is the icon projects will use:

<img width="589" alt="Screenshot 2019-04-27 at 23 43 05" src="https://user-images.githubusercontent.com/16776042/56855839-7d295a00-6946-11e9-809d-f7789c652bbe.png">

**Comment by chrismaltby** [comment]
Commit b266a2af4b5074e98c3215c9121be955fdbcb3de adds support for opening directly from project files in Windows but the user first needs to select GB Studio from the list manually as shown in  Derek's screenshot.

To add the window registry I found this https://github.com/CatalystCode/windows-registry-node which has an `associateExeForFile` helper but I'm having trouble installing the module dependencies. Then there's also https://www.npmjs.com/package/regedit which I believe has no native dependencies but seems a bit more manual. I had a look at the link you sent Derek and did some research myself but I don't really know enough about the Windows registry to know what commands need to be run to associate the exe, the extension and the icon file together.

**Comment by thomas-alrek** [comment]
Great. I will close this issue then! 🙂
