### ISSUE TITLE
Make info area of scenes smaller

### ISSUE THREAD

**Issue by Rebusmind** [chrismaltby/gb-studio#861]
**Is your feature request related to a problem? Please describe.**
The area that shows the amount of actors, frames and triggers is pretty big, using a lot of unused space, which makes it harder to put scenes that are connected closer together. 

**Describe the solution you'd like**
It's not a huge issue, but it would be cool if that area would only be as high as that one line of text.

**Comment by DeerTears** [comment]
It changed a little bit in 3.0
![image](https://user-images.githubusercontent.com/47726614/145861970-fd5a444f-a4eb-4f10-98b0-ccbea64e1901.png)

But compared to how it was in 2.0 it's not a huge difference?
![image](https://user-images.githubusercontent.com/47726614/145862224-f85edc52-e0f8-4ce5-b995-5ba4c6c6eaf7.png)

If anything I think the font size got bigger and the info panel scaled with it. @Rebusmind Do you have a project that's been significantly harder to see because of this change to the info panel?

**Comment by Rebusmind** [comment]
It's just a lot of unused space. I think it would look better if it was the same height as the top border.

**Comment by Rebusmind** [comment]
The area is now smaller. Thanks! :)
