### ISSUE TITLE
[Request] Copy/Paste Actors across scenes

### ISSUE THREAD

**Issue by KitF** [chrismaltby/gb-studio#99]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
A feature

* **What is the current behavior?**
Can't copy/paste actor scripts across scenes

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
I want to be able to move or copy an actor between scenes. I set up a test in the initial scene, but when I went to move it to a new scene, I found that I couldn't.

* **What is the motivation / use case for changing the behavior?**
Moving NPCs between scenes after testing them in a proof of concept without having to copy/paste each event individually

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: [Windows]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by chrismaltby** [comment]
Good idea. I'm thinking first add a button here on scripts, actors and triggers

<img width="308" alt="Screenshot 2019-04-30 at 22 21 17" src="https://user-images.githubusercontent.com/16776042/56994234-64af7e80-6b96-11e9-8f43-9119dfb19550.png">

that would open a dropdown with
- Copy Script
- Replace Script
- Paste Script Before
- Paste Script After
- Delete Script

Allowing you to move scripts around a lot easier.

We should also have keyboard shortcuts Cmd/Ctrl + C, and Cmd/Ctrl + V to copy/paste the selected actors / triggers (paste would place on the scene directly under the mouse) 

Then I also think you should be able to move actors and triggers between scenes by dragging them, same as you can now for scene transition destinations and the player start position.

**Comment by HeyItsLollie** [comment]
Would it make sense to have prefabs for instanced actors/triggers?

You could create an actor that is set up with common events, for example: a specific character with blank text fields that always triggers certain events when they enter/exit the scene, or an item with a blank "set flag" field that always plays a jingle when collected. Any time you need a specific actor, you could just select it from an assets/prefabs list and drag it into the scene.

GB Studio could reference the prefab, lock pre-existing events on a prefab so that only their variables can be edited (if you want to remove events that come with the prefab, you have to break prefab instance), and piggy-back additional events on top of the reference for the prefab. If you ever need to update a prefab project-wide, you could edit the prefab directly, and your changes would automatically be available across the whole project.

**Comment by chrismaltby** [comment]
Prefabs is a good idea definitely, think that’s an idea for a future version though. Just going to put copy/paste in for now and we could revisit this later.

**Comment by chrismaltby** [comment]
As of 7d4ab30978c2b44f9e6a25cb3dcddd7d68a944b1 you can now copy/paste scripts as I suggested. Also you can copy/paste actors, triggers and even entire scenes by using Cmd/Ctrl + C, and Cmd/Ctrl + V and can drag actors and triggers between scenes.
